### ISSUE TITLE
Project Sanity - the dependency management plan

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#1176]
# Dependency Management Plan
Over v6 and v7 there will be breaking changes on how dependencies are managed (0L is currently on v5).
From v6 we are beginning to split up the modules (Rust crates) so that upstream platform changes can be rebased without conflict.

### v6 - (IN PROGRESS) begin isolating 0L changes from monorepo, make rebases less painful 
- Isolate the Rust types 0L uses away from `diem-types` crate, and extend by making opaque types where necessary in ol/ol-types crate.
- Export testing tools so that 0L tests can use shared testsuite crates without needing to modify the code, or include tests in monorepo. This is complete for "smoke-tests" https://github.com/OLSF/libra/commit/6106c0730b9953cb8021b5dfc33f9e48cf578a34
- Refactors so that we use the official Sui Move repo, instead of our fork of the diem/move repo.

### v7 abandon the monorepo, make rebases automatic
- Keep a "Light Fork" of the upstream monorepos Move/Aptos/Sui up-to-date weekly. These repos have very light changes to public visibility of structs. We will offer these patches as PRS in upstream. But our goal is that these changes are very light, and allow for automatic rebasing of all changes.
- All command line tools (including `libra-node`) will be authored by 0L and live in an 0L repo, which import from Light Fork. 
- Some CLI tools may just be importing upstream crates, making a thin wrapper (e.g. `diem-transaction-generator`).  
- In other cases the modules and structs of the upstream are imported and extended in the 0L cli tools. 
- TBD There may be binaries where this strategy may not work cleanly. One hypothesis is that another monorepo fork be maintained in order to make isolated changes to a single module.
- Where tools are unmaintained by upstream we will keep in a separate repo: e.g. Shuffle dev tools.

**Comment by simsekgokhan** [comment]
## v7

### Info
/// 0L dev. branches:
aptos-0L: https://github.com/simsekgokhan/aptos-core-0L/tree/v7
Move-0L: https://github.com/simsekgokhan/move-0L/commits/v7
Libra:       https://github.com/0LNetworkCommunity/libra/tree/v7

/// Upstream branches
https://github.com/aptos-labs/aptos-core/commits/main
https://github.com/move-language/move/commits/main

/// How to find Aptos compatible Move version (they seem to depend on commits from Move aptos-main or main branch)
Find the version here -> https://github.com/aptos-labs/aptos-core/blob/main/Cargo.toml#L461
**e.g.**
Latest compatible Move version is : `... = { git = "https://github.com/move-language/move", rev = "080cb5c4feddaa87990faa4767156e422c7ec90d" }` -> https://github.com/move-language/move/commit/080cb5c4feddaa87990faa4767156e422c7ec90d <Feb 4, 2023>

### Plan/Steps
- [x] Remove all Diem files from Libra repo, move `ol/` folders https://github.com/0LNetworkCommunity/libra/tree/main/ol into root `src/` in Libra v7 (abandon the monorepo), have buildable packages where possible.
- [x] Create a lite fork of https://github.com/move-language/move with 0L patches which will allow for automatic rebasing when pulling from upstream. Done, see -> https://github.com/simsekgokhan/move-0L/tree/v7
**Example**: https://github.com/simsekgokhan/move/tree/v7-move-6-dec-2022 which is forked (and 0L patched) from upstream Move version 6-dec-2022, is rebased to upstream move-20-dec-2022 with one Github click `Sync fork` (alternatively git cmd `Rebase head to`), result: https://github.com/simsekgokhan/move-0L/tree/v7-move-20-dec-2022.
- [ ]  [Ongoing] Create a lite fork of Aptos with 0L patches which will allow for automatic rebasing when pulling from upstream -> aptos-0L: https://github.com/simsekgokhan/aptos-core-0L/tree/v7
- [ ] Make sure libra, aptos-0L and move-0L builds
- [ ] Make sure libra tests passes
- [ ] Double check: Move aptos-0L patches into libra as much as possible
- [ ] ...

**Comment by simsekgokhan** [comment]
## v7 continued...

### Todo Later / Discuss
- [ ] move 0L files `diem-move/writeset-transaction-generator/templates/*.move` to libra repo ? 
- [ ] aptos-move/vm-genesis/src/lib.rs -> encode_genesis_change_set() and all other changes
- [ ] diem-move/parallel-executor/* - many and major changes
- [ ] diem-move/mvhashmap/* - many and major changes
- [ ] diem-move/e2e-testsuite/src/tests/ol_autopay_create.rs*
- [ ] `cp -R diem-move/diem-framework/core/transactional-tests/0L ../aptos-core-0L/aptos-move/aptos-transactional-test-harness/tests`
- [ ] diem-move/e2e-tests/src/ol_oracle_setup.rs
- [ ] diem-move/diem-vm/src/*
- [ ] cargo test -p aptos-transactional-test-harness // aptos-move/aptos-transactional-test-harness/tests/tests.rs // diem-move/diem-framework/tests/ol_transactional_tests.rs
- [ ] diem-move/diem-framework/src/release.rs
- [ ] Discuss: How to patch Aptos move from diem-move/diem-framework/DPN/sources/* .move ? Problem: move files are almost totally changed in Aptos -> https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/framework/aptos-framework/sources and https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/framework/aptos-stdlib/sources
- [ ] Discuss: 38 pieces of 0L move files need to be rewritten? (reason: the Diem dependencies are gone in Aptos). Should we put them in libra or in aptos?  - diem-move/diem-framework/DPN/sources/0L/*.move
- [ ] 11 pieces of 0L move scripts, same issues as the item above - diem-move/diem-framework/DPN/sources/0L_transaction_scripts/ol_*.move

**Comment by simsekgokhan** [comment]
## v7 continued...

## Notes

### 1. Missing files (thus, 0L patches) in aptos-core:
diem-move/writeset-transaction-generator/src/main.rs
diem-move/transaction-replay/*
diem-move/e2e-tests-replay/*
config/management/genesis/*
&nbsp;&nbsp;   builder.rs, command.rs, genesis.rs, init.rs, key.rs, layout.rs, lib.rs, 
&nbsp;&nbsp;   ol_create_repo.rs, ol_mining.rs, ol_node_files.rs, ol_seeds.rs
&nbsp;&nbsp;   storage_helper.rs, validator_builder.rs, validator_config.rs, verify.rs, waypoint.rs

config/management/*
&nbsp;&nbsp;   secure_backend.rs, validator_config.rs

config/src/config/json_rpc_config.rs

crates/diem-wallet/*

diem-move/diem-framework/
diem-move/diem-framework/core/transactional-tests/*

diem-move/diem-framework/DPN/sources/* .move
( move files almost totally changed, new path -> aptos-move/framework/aptos-framework/sources/*.move )

### 2.a. Aptos move framework

aptos-move/framework/aptos-framework/sources
(cargo r -p aptos-framework -- release)
&nbsp;&nbsp;    account.move
&nbsp;&nbsp;    aptos_coin.move
&nbsp;&nbsp;    block.move
&nbsp;&nbsp;    ...

aptos-move/framework/aptos-stdlib/sources
&nbsp;&nbsp;    any.move
&nbsp;&nbsp;    debug.move
&nbsp;&nbsp;    hash.move
&nbsp;&nbsp;    ...

aptos-move/framework/move-stdlib/sources
&nbsp;&nbsp;    bcs.move
&nbsp;&nbsp;    error.move
&nbsp;&nbsp;    hash.move
&nbsp;&nbsp;    signer.move
&nbsp;&nbsp;    vector.move
&nbsp;&nbsp;    ...


### 2.b. Move-lang

language/move-stdlib/src/natives
&nbsp;&nbsp;    bcs.rs       // Ok - implemented only here
&nbsp;&nbsp;    ol_vdf.rs   // Ok - impl. only here
&nbsp;&nbsp;    string.rs   // Nok - duplicate impl. in aptos repo
&nbsp;&nbsp;    vector.rs  // Nok - duplicate impl. in aptos repo

Important: 
There are duplicate `move-stdlib` files here https://github.com/move-language/move/tree/main/language/move-stdlib/sources which has no effect when changed (tested and verified). Which means, if we want to patch vector, we need to change `aptos-labs/aptos-core/tree/main/aptos-move/framework/move-stdlib/sources/vector.move` not `move-language/move/tree/main/language/move-stdlib/sources/vector.move` (which is confusing and looks wrong)

**Comment by simsekgokhan** [comment]
### Notes - continued...

### 3. Various Aptos tests

/aptos-move/aptos-transactional-test-harness/tests
(cargo t -p aptos-transactional-test-harness -- exec)
&nbsp;&nbsp;    call_function.exp
&nbsp;&nbsp;    call_function.move
&nbsp;&nbsp;    execute_script.exp
&nbsp;&nbsp;    execute_script.move
&nbsp;&nbsp;    publish_module.exp
&nbsp;&nbsp;    publish_module.move
&nbsp;&nbsp;    table.exp
&nbsp;&nbsp;    table.move
&nbsp;&nbsp;    write_set_too_large.exp
&nbsp;&nbsp;    write_set_too_large.move

aptos-move/framework/move-stdlib/tests
(cargo r -p aptos -- move test --package-dir aptos-move/framework/move-stdlib/ -f vdf)
&nbsp;&nbsp;    * ol_vdf_tests.move
&nbsp;&nbsp;    bcs_tests.move
&nbsp;&nbsp;    string_tests.move
&nbsp;&nbsp;    vector_tests.move

aptos-move/e2e-move-tests
&nbsp;&nbsp;    gas.rs
&nbsp;&nbsp;    transaction_fee.rs
&nbsp;&nbsp;    token_event_store.rs
&nbsp;&nbsp;    e2e-move-tests/src/tests/max_loop_depth.data/pack-bad/sources/test.move

aptos-move/e2e-move-tests/src/tests
&nbsp;&nbsp;    account.rs
&nbsp;&nbsp;    account_universe.rs
&nbsp;&nbsp;    on_chain_configs.rs

aptos-move/e2e-testsuite/src/tests
&nbsp;&nbsp;    create_account.rs
&nbsp;&nbsp;    genesis_initializations.rs
&nbsp;&nbsp;    mint.rs
&nbsp;&nbsp;    module_publishing.rs
&nbsp;&nbsp;    ...
