### ISSUE TITLE
Patch diem-core 1.3.0 

### ISSUE THREAD

**Issue by simsekgokhan** [OLSF/libra#616]
## Info:

/// Dev. branch  
https://github.com/OLSF/libra/commits/v5

/// Upstream commit used for patching: 
diem-core-v1.3.0 - July 7, 21
https://github.com/diem/diem/commits/diem-core-v1.3.0

## Next Actions: 
- [x] Merge v5_old_diem-1.2.0 into diem-core 1.3.0, resolve all conflicts
- [x] `cargo clean`, `cargo b --all` and `cargo b --all-targets`
- [x] Use `cargo c` instead of `cargo b` for quick iteration
- [x] Resolve all Move modules/transaction scripts errors, build diem-framework -> `ol\utils\build-stdlib.sh`
- [x] Resolve all Rust build errors for all packages ->  `cargo b --all` and `cargo b --all-targets`
- [x] Get all move-lang-functional-tests build & pass -> `PRETTY=1 cargo test -p move-lang-functional-tests -- 0L/ > /opt/27.jul.txt 2>&1` (start w/ `chained_from_genesis` or `persistence`)
- [x] Get `move-lang-functional-tests` changes reviewed
- [x] [1 fail remaining] Get all e2e tests build & pass -> `PRETTY=1 cargo test -p language-e2e-testsuite -- --nocapture ol_`
- [x] Get swarm working
- [x] Get mining working
- [x] Pull latest changes from main
- [x] Make sure swarm works & get integrations tests pass, more -> State of ol\integretion-tests on v5 #596
- [x] Final check - all 0L tests and swarm work
- [x] #642
- [x] Final cargo clean, cargo b --all and cargo b --all-targets

# Tests refactor
These are disabled tests which may be deprecated, but whose functions are confirmed to work in other CI tests.
- [x] e2e test for upgrade. Need to find a way to see the transaction log, only getting Misc Error which is not useful https://github.com/OLSF/libra/issues/641
- [x] ol/types/account::val_config_ip_address() test on serializing network addresses. Unsure why this is different from Libra https://github.com/OLSF/libra/issues/641

## Notes: 

//// swarm 5 accounts alice bob etc..
[language/tools/vm-genesis/src/lib.rs:405] owner_address = 4C613C2F4B1E67CA8D98A542EE3F59F5
[language/tools/vm-genesis/src/lib.rs:405] owner_address = 88E74DFED34420F2AD8032148280A84B
[language/tools/vm-genesis/src/lib.rs:405] owner_address = E660402D586AD220ED9BEFF47D662D54
[language/tools/vm-genesis/src/lib.rs:405] owner_address = 9E6BB3A75E9618FBA057E86E69338C94
[language/tools/vm-genesis/src/lib.rs:405] owner_address = 5709AFA1D0FBB40B171AA03D457DB72A

**Comment by simsekgokhan** [comment]
## Next Actions: 
- [ ] Merge `v5_old_diem-1.2.0` into `diem-core 1.3.0`, resolve all conflicts, commit/push
- [ ] Solve ..

**Comment by simsekgokhan** [comment]
Remaining failing `move-lang-functional-tests`:
```
failures:
    functional_testsuite::0L/autopay/instructions_balance.move        
    functional_testsuite::0L/autopay/instructions_inflow.move   
    functional_testsuite::0L/autopay/autopay_escrow_percentage.move   
```

**Comment by simsekgokhan** [comment]
Remaining/todo-later failing move-lang-functional-tests:

```
test_successful_upgrade_txs
```
------------------------------------

Details:  

Followings done, still fails:  
https://github.com/OLSF/libra/wiki/Stdlib-Upgrade-payload
https://github.com/OLSF/libra/wiki/Stdlib-Upgrade-payload-(v5)

```
cargo test -p language-e2e-testsuite -- --nocapture test_successful_upgrade_txs

   Compiling language-e2e-testsuite v0.1.0 (/home/gsimsek/libra-fork/language/e2e-testsuite)
    Finished test [unoptimized + debuginfo] target(s) in 17.93s
     Running unittests (target/debug/deps/language_e2e_testsuite-980912f51ca17c5d)

running 1 test
OK create_and_initialize_main_accounts =============== 
Initializing with env: test
0 ======== Create Owner Accounts
[language/tools/vm-genesis/src/lib.rs:412] owner_address = 06505CCD81E562B524D8F656ABD92A15
[language/tools/vm-genesis/src/lib.rs:412] owner_address = DE589EC6B85A4A1A58BE166C38551CC2
[language/tools/vm-genesis/src/lib.rs:412] owner_address = B000D8E1919132C664A36C0FDF986407
[language/tools/vm-genesis/src/lib.rs:412] owner_address = 3C36BD759B51F1C9B7F4258896FCFE6C
1 ======== Create OP Accounts
2 ======== Link owner to OP
3 ======== OP sends network info to Owner config
4 ======== Add owner to validator set
OK create_and_initialize_owners_operators =============== 
OK Genesis subsidy =============== 
created new validator accounts
registered new validator accounts
======== round is 0
minted tokens for validators
======== round is 0
created operator account
validators set their operator account
======== round is 0
registered validator configs
registered and reconfigured validators
======== round is 0
minerstate_helper_script executed successfully
minerstate_commit executed successfully
thread 'tests::ol_upgrade_oracle::test_successful_upgrade_txs' panicked at 'assertion failed: `(left == right)`
  left: `Ok(MISCELLANEOUS_ERROR)`,
 right: `Ok(EXECUTED)`', language/e2e-testsuite/src/tests/ol_upgrade_oracle.rs:243:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::ol_upgrade_oracle::test_successful_upgrade_txs ... FAILED

failures:

failures:
    tests::ol_upgrade_oracle::test_successful_upgrade_txs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 150 filtered out; finished in 54.01s

error: test failed, to rerun pass '-p language-e2e-testsuite --lib'
```

**Comment by simsekgokhan** [comment]
### Swarm last account problem:

This is the expected accounts: 

```//// swarm 5 accounts alice bob etc..
[language/tools/vm-genesis/src/lib.rs:405] owner_address = 4C613C2F4B1E67CA8D98A542EE3F59F5
[language/tools/vm-genesis/src/lib.rs:405] owner_address = 88E74DFED34420F2AD8032148280A84B
[language/tools/vm-genesis/src/lib.rs:405] owner_address = E660402D586AD220ED9BEFF47D662D54
[language/tools/vm-genesis/src/lib.rs:405] owner_address = 9E6BB3A75E9618FBA057E86E69338C94
[language/tools/vm-genesis/src/lib.rs:405] owner_address = 5709AFA1D0FBB40B171AA03D457DB72A
```

This is what we have, the 5th address is different:
```
OK create_and_initialize_main_accounts =============== 
Initializing with env: test
0 ======== Create Owner Accounts
[language/tools/vm-genesis/src/lib.rs:413] owner_address = 4C613C2F4B1E67CA8D98A542EE3F59F5
[language/tools/vm-genesis/src/lib.rs:413] owner_address = 88E74DFED34420F2AD8032148280A84B
[language/tools/vm-genesis/src/lib.rs:413] owner_address = E660402D586AD220ED9BEFF47D662D54
[language/tools/vm-genesis/src/lib.rs:413] owner_address = 9E6BB3A75E9618FBA057E86E69338C94
[language/tools/vm-genesis/src/lib.rs:413] owner_address = 4E1F81F77024B56DBB853CE7ED8E1C7E
```

**Comment by simsekgokhan** [comment]
### Mining error:

```     
Running `target/debug/miner --swarm-path /opt/swarm_temp --swarm-persona alice start`
miner config file not existing: "/opt/swarm_temp/0/0L.toml"
Info: Got tx params from swarm
Fetching remote tower height: http://localhost:40697/, 4C613C2F4B1E67CA8D98A542EE3F59F5
Aug 16 14:34:26.958  INFO ureq::unit: sending request POST http://localhost:40697/    
Aug 16 14:34:26.963  INFO ureq::unit: sending request POST http://localhost:40697/    
Aug 16 14:34:26.965  INFO ureq::unit: sending request POST http://localhost:40697/    
Aug 16 14:34:26.967  INFO ureq::unit: sending request POST http://localhost:40697/    
Error fetching remote state: 
  Error { inner: Inner { kind: JsonRpcError, source: None,
      json_rpc_error: Some(JsonRpcError { code: -32602, message: "method_not_found'", 
      data: None }) } 
}
Failed fetching remote state: 
    Error fetching remote state: 
    Error { inner: Inner { kind: JsonRpcError, source: None, 
        json_rpc_error: Some(JsonRpcError { code: -32601, message: "method_not_found'", data: None }) } 
    }
url: http://localhost:40697/
Block 752 Mining VDF Proof
```
