### ISSUE TITLE
v5 `0L todo`s

### ISSUE THREAD

**Issue by simsekgokhan** [OLSF/libra#642]
Some `0L todo`s in the code which requires review.

- [x] https://github.com/OLSF/libra/blob/v5/json-rpc/src/methods.rs#L420
- [x] https://github.com/OLSF/libra/blob/v5/language/move-prover/interpreter/src/lib.rs#L103
- [x] https://github.com/OLSF/libra/blob/v5/language/diem-framework/modules/DiemAccount.move#L2938 and L2952
- [x] https://github.com/OLSF/libra/blob/v5/language/diem-tools/oncall-trainer/src/init.rs#L116
- [x] https://github.com/OLSF/libra/blob/v5/language/move-prover/bytecode/src/packed_types_analysis.rs#L55
- [x] https://github.com/OLSF/libra/issues/593
- [x] I guess this is done already? Need to remove the commented lines. https://github.com/OLSF/libra/blob/v5/ol/cli/src/node/query.rs#L130
- [x] https://github.com/OLSF/libra/blob/v5/types/src/account_config/constants/coins.rs#L17

**Comment by simsekgokhan** [comment]
@lpgeiger FYI.
