### ISSUE TITLE
OL Stdlib Integrations

### ISSUE THREAD

**Issue by 0o-de-lally** [OLSF/libra#68]
- [x] Epoch Change triggers https://github.com/OLSF/libra/issues/70
- [x] Voting power updated by Node Weight: https://github.com/OLSF/libra/issues/65

- [x] Redeem stores and returns the Tower Height https://github.com/OLSF/libra/issues/58 (Do this one last, lower priority)
