### ISSUE TITLE
Merge with Diem upstream 1.4.1

### ISSUE THREAD

**Issue by simsekgokhan** [OLSF/libra#775]
## Info

/// Dev. branch
https://github.com/OLSF/libra/commits/v6
Latest 0L commit in this branch: https://github.com/OLSF/libra/commit/5a814036d22c2ca1577cb14fbfc9a4cb2baf8f5b @14-feb-2022

/// Diem upstream being patched:
[State Sync] Support failure handling for the storage synchronizer
https://github.com/diem/diem/tree/0de006b7ff52c32f0e267d9188975f52a826eb39 (Jan 25, 2022)
// Compatible Move version:  
https://github.com/diem/move/tree/98ed299a7e3a9223019c9bdf4dd92fea9faef860 (Jan 8, 2022)

/// Additional Diem commits merged
/// (17 commits on top of commit [State Sync] Support failure .. Jan 25, 2022)
trivial: remove DB::get_latest_state_root(), Feb 19, 2022
https://github.com/diem/diem/commits/50925260829a84d7a07b7f1922fcefc3b8147a2d

/// Additional commits merged from 0L release-v5.2.0
Commits up to Aug 20, 2022, update StateSyncConfig parameters
https://github.com/OLSF/libra/commits/release-v5.2.0

## Problems/Notes

0L Patching Tips
- `XDX` becomes `GAS`

In diem 1.4, 
- Folder `common` became `crates`
- Folder 'language' moved to https://github.com/diem/move/ and 'diem-move' folder
- No `testsuite/cli/`
- No `testsuite/cluster-test`
- No `testsuite/diem-swarm`
- functional-tests is now called transactional_tests, 
  use `NODE_ENV="test" cargo test -p diem-framework --test ol_transactional_tests filename` instead of `cargo test -p move-lang-functional-tests -- filename` 
- `CoreAddresses::DIEM_ROOT_ADDRESS()` becomes `@DiemRoot` same for `@VMReserved`

Difficult patches and/or todo-laters:
- [x]  mempool/src/shared_mempool/tasks.rs
- [ ] Cannot include `testsuite/cli/src/ol_node_commands.rs` and `testsuite/cli/src/ol_oracle_commands.rs` since there is no `testsuite/cli/` in Diem
- -------- Notes from first/old merge attempt:
- `DIEM_ROOT_ADDRESS()` became `@DiemRoot`, `CURRENCY_INFO_ADDRESS()` became ` @CurrencyInfo` etc..
- No `language/move-vm/natives/` 
- Major changes in `language/move-vm/runtime/src/`, so will be for 0L patch
- No `language/tools/vm-genesis/src/genesis_gas_schedule.rs`

Difficult patches/todo-later:
- [ ]  `config/management/genesis/src/genesis.rs` - no `pub fn operator_registrations()`, `operator_assignments()`, major change in `fn execute(self)`
- [ ] Major changes in `language/tools/vm-genesis/src/lib.rs` in general and specifically in `create_and_initialize_owners_operators()`, `pub struct Validator`

Discuss:
- [ ]  Is this todo? `language/diem-framework/modules/DiemAccount.move` ::  `public fun balance()`

## First pass fork and port

- [x] [DIEM] Choose latest diem-core version `diem-core-v1.4.1` - https://github.com/diem/diem/releases.
- [x] From the chosen diem-core version, checkout a new 0L branch e.g. `v6-base-diem-1.4.1` - this will be the diem code without 0L changes.
- [x] From the chosen diem-core version, checkout a new 0L branch e.g. `v6-temp` - this will be the diem code with the 0L changes.
- [x] Merge current 0L main dev. branch into (`v6-temp`), resolve all conflicts
- [x] Double check all conflicts are solved, search `<<<<<<< HEAD`
- [x] Checkout a new `v6` from latest 0L commit which will be patched. Manually copy all files of `v6-temp` except `.git` folder into new `v6` (to preserve 0L commit history)
- [x] Solve all Move modules and transaction scripts build errors (before Rust since this step creates Rust files). Use `ol\utils\build-stdlib.sh`
- [x] Solve all Rust build errors/warnings for all packages -> Use `cargo c --all` and `cargo c --all-targets`
- [x] Double check & try to fix`// 0L todos` in code
- [x] [MOVE-REPO] Search/find compatible move version in diem repo `e.g. "git = "https://github.com/diem/move", rev = "98ed299..." }"`
- [x] From this rev/commit, checkout a new move-0L branch e.g. `v6-base` - this will be the Move code without 0L changes.
- [x] From this rev/commit, checkout a new move-0L branch e.g. `v6-temp` - this will be the Move code WITH 0L changes.
- [x] Merge current move-0L main dev. branch into (`v6-temp`), solve all conflicts
- [x] Double check all conflicts are solved, search `<<<<<<< HEAD`
- [x] Checkout a new `v6` from latest move-0L commit that will be patched. Manually copy all files of `v6-temp` except `.git` folder into new `v6` (to preserve the 0L commit history)
- [x] Solve all Rust build errors/warnings for all packages ->  `cargo c --all` and `cargo c --all-targets`
- [x] Double check & try to fix `// 0L todos` in code
- [x] Try to find and patch the new code for 0L patched folders/files which are deleted/renamed in new Diem. 
- [x] Discuss: Move Diem related 0L code from move-0L to libra repo (reason: causing cyclic dependency type errors)
- [x] `cargo clean`, `cargo c --all` and `cargo c --all-targets` - make sure no errors or warnings
```
// Some core paths and files to start fixing:
- config/ 
- language/tools/vm-genesis/
- Genesis.move
```

- [x] Make sure all the coins patched as "GAS" in types/src/account_config/constants/coins.rs

E.g.
```
//////// 0L ////////
// other coins besides GAS are only used for tests, and come from upstream
pub const GAS_NAME: &str = "GAS";
pub const GAS_IDENTIFIER: &IdentStr = ident_str!(GAS_NAME);
pub const XUS_NAME: &str = "GAS";
pub const XUS_IDENTIFIER: &IdentStr = ident_str!(XUS_NAME);
pub const XDX_NAME: &str = "GAS";
pub const XDX_IDENTIFIER: &IdentStr = ident_str!(XDX_NAME);
```

- [x] Move error prints not working - double check: Look for the string [print] or [move print]"
- [x] Get all `ol_transactional_tests` build & pass -> `PRETTY=1 NODE_ENV="test" cargo test -p diem-framework --test ol_transactional_tests > /opt/27.jul.2x.txt 2>&1` (Hint: start with chained_from_genesis, persistence, *_meta,  *_meta_epoch, init_miner_state, genesis_0L, gas_init, pow_verify_initialization. Do the cases folder last)
```
Hint: Tests should use 0L coin "GAS" 
```

- [x] Make sure we have 0L patched SALT and test `val_config_ip_address` in `ol/types/src/account.rs` is passing

```
// types/src/network_address/encrypted.rs
/////// 0L /////////
pub const HKDF_SALT: [u8; 32] = [
    0xdf, 0xc8, 0xff, 0xcc, 0x7f, 0x62, 0xea, 0x4e, 0x5b, 0x9b, 0xc4, 0x1e, 0xe7, 0x96, 0x9b, 0x44,
    0x27, 0x54, 0x19, 0xeb, 0xaa, 0xd1, 0xdb, 0x27, 0xd2, 0xa1, 0x91, 0xb6, 0xd1, 0xdb, 0x6d, 0x13,
];
```

## TODO
- [x] Make upgrade_foo() fixtures. This is needed for e2e and integration test which checks if the stdlib can be upgraded.
./libra/ol/fixtures/upgrade_payload# make fixtures -f make-e2e-upgrade-fixtures.mk 
- [ ] Get all e2e tests build & pass -> `PRETTY=1 cargo test -p language-e2e-testsuite -- --nocapture ol_`
- [ ] `// 0L todo diem 1.4.1` tags in code needs review from another person
- [ ] Get swarm working
- [ ] Make sure all of the swarm account addresses are same as before:  
```
OK create_and_initialize_main_accounts =============== 
Initializing with env: test
0 ======== Create Owner Accounts
[language/tools/vm-genesis/src/lib.rs:413] owner_address = 4C613C2F4B1E67CA8D98A542EE3F59F5
[language/tools/vm-genesis/src/lib.rs:413] owner_address = 88E74DFED34420F2AD8032148280A84B
[language/tools/vm-genesis/src/lib.rs:413] owner_address = E660402D586AD220ED9BEFF47D662D54
[language/tools/vm-genesis/src/lib.rs:413] owner_address = 9E6BB3A75E9618FBA057E86E69338C94
[language/tools/vm-genesis/src/lib.rs:413] owner_address = 4E1F81F77024B56DBB853CE7ED8E1C7E
      // Note: 5th address is created randomly, it might change e.g. https://github.com/OLSF/libra/issues/645
```
- [ ] Get mining working
- [ ] Get integrations tests pass https://github.com/OLSF/libra/tree/main/ol/integration-tests
- [ ] Update https://github.com/OLSF/libra/blob/main/ol/documentation/core-devs/how_to_pull_new_diem_code.md
- [ ] Update `ol/documentation/core-devs/writing_and_using_native_functions_in_move.md` if needed. e.g. for Diem 1.4.1, use these two commits to update the doc.:
      . https://github.com/OLSF/move-0L/commit/5ff91d82a4969f1efa18dfc18965a37300d8f2e4
      . https://github.com/OLSF/move-0L/commit/8d785cc4448a6c195b3911e6b6c1c804aacf92b4
- [ ] ..

## Get latest changes from 0L active branch.

- [x] Merge latest changes from main.
- [ ] Final check - all 0L tests and swarm work
- [ ] Final cargo clean, cargo b --all and cargo b --all-targets
- [ ] Update carpe `rust-toolchain` file to be same as libra

### Some more useful info might be found in these issues:  
https://github.com/OLSF/libra/issues/616  
https://github.com/OLSF/libra/issues/530 (this has the steps for manual patching instead of git auto-merge - due to name change "libra" to "diem")
